<h1>Tratamento de erros no Java - Exceptions</h1>

Componentes de software podem ter problemas durante a execução e gerar erros como:

- Terminar o programa;
- Retornar uma mensagem de erro indicando uma falha;
- Retornar e ignorar o problema;
- Chamar um método para tratar o erro, entre outras.

Os problemas mais comumente encontrados são:

- Falha na aquisição de um recurso (new, open...);
- Tentativa de fazer algo impossível (divisão por zero, índice de um array inválido...);
- Outras condições inválidas (lista vazia, overflow...).

Para contornar estes empecilhos, utilizamos o recurso chamado **Exceções (Exceptions)**.

<h2>1. Exceptions</h2>

As Exceções (Exceptions) são uma indicação de um problema que ocorre durante a execução de um programa. Em Java é possível tratar as exceções que poderiam ocorrer para que o programa continue ou termine de forma elegante. As Exceções são Objetos criados a partir de classes especiais, que são “disparados” quando ocorrem condições excepcionais. 

<h3>1.2 Tipos de erros</h2>

Os erros que acontecem nas aplicações Java estão classificados em 3 categorias:

1. **Erros de lógica:** Esta categoria abrange erros na construção do Algoritmo. Este tipo de erro devem ser corrigidos pelo programador

- **Exemplos:** Limites do vetor ultrapassados, divisão por zero, entre outros;

2. **Erros devido a condições do ambiente de execução:** Esta categoria abrange erros na infraestrutura onde a aplicação está sendo executada. Este tipo de erro foge do controle do programador, mas podem ser contornados em tempo de execução;

- **Exemplos:** arquivo não encontrado, rede fora do ar, entre outros;

3. **Erros graves:** São erros que simplesmente travam o sistema e não há nada o que fazer. Este tipo de erro foge do controle do programador e não podem ser contornados;

- **Exemplo:** falta de memória, erro interno do Java, entre outros.

Veja o exemplo abaixo:

```java
package com.generation.exc_divisao;

import java.util.Scanner;

public class Divisao {

	static Scanner ler = new Scanner(System.in);
	
	public static void main(String[] args) {
		
		int dividendo = 0;
		int divisor = 0;
			
		System.out.println("Digite o Dividendo: ");
		dividendo = ler.nextInt();
				
		System.out.println("Digite o Divisor: ");
		divisor = ler.nextInt();
				
		divide(dividendo, divisor);

	}

	public static void divide(int dividendo, int divisor) {
		System.out.println("Divisão = " + (dividendo / divisor));
	}

}
```

Experimente fazer uma divisão por zero. Você verá o resultado abaixo no seu console:

<div align="center"><img src="https://i.imgur.com/aTXz9R1.png" title="source: imgur.com" /></div>

Experimente inserir uma String ao invés de um numero no divisor. Você verá o resultado abaixo no seu console:

<div align="center"><img src="https://i.imgur.com/IT55yyi.png" title="source: imgur.com" /></div>

Observe que nos 2 exemplos o Java retornou **mensagens de erro diferentes**. 

Quando uma exceção é lançada, ela interrompe o **fluxo normal** do programa, ou seja, o fluxo do programa **segue** a exceção. Se o método onde ela ocorrer não a capturar a exceção ela será **propagada** para o método que chamar esse método e assim por diante. Se **ninguém** capturar a exceção, ela causará o término da aplicação. Agora se em algum lugar ela for capturada, **o controle pode ser recuperado**.

Um bom **Sistema de Tratamento de Exceções** procura sempre: 

- Se antecipar aos problemas (uma das tarefas da pessoa desenvolvedora);
- Reverter situações de erro que podem ser revertidas;
- Buscar a **Solução ideal** para o tratamento de problemas separado do código principal.

Com o tratamento de exceções, o programa captura e trata, isto é, lida com a exceção. Para capturar e lidar com as exceções utilizaremos a estrutura **Try -Catch**.

<h3>1.3. Estrutura try-catch</h3>

A estrutura de como tratar um erro ou exceção é composta por 3 estruturas básicas:

- **try:** é usada para indicar um bloco de código que possa lançar (throw) uma exceção.
- **catch:** serve para manipular as exceções, ou seja, tratar o erro.
- **finally:** sempre será executado depois do bloco try/catch.

Na imagem abaixo, vemos a sintaxe da estrutura try-catch dentro do código Java:

<div align="center"><img src="https://i.imgur.com/Uwvqs3q.png" title="source: imgur.com" /></div>

O **Bloco try** contém o código que pode lançar (throw) uma exceção. Ele consiste na palavra – chave try seguida por um bloco de código entre chaves.

O **Bloco Catch** captura e trata uma exceção. Ele começa com a palavra-chave catch. Dentro dos parênteses deve ser inserido o parâmetro de exceção, que identifica o tipo da exceção. O bloco de código entre as chaves será executado quando uma exceção do tipo adequado ao parâmetro ocorre.

O **Bloco Finally** é opcional em uma instrução try. Se estiver presente, ele será colocado depois do último bloco Catch. Ele será executado somente se uma exceção for lançada no bloco try correspondente ou qualquer um dos seus blocos catch correspondentes. Em geral, ele contém código de liberação de recursos do sistema.

Na imagem abaixo, vemos a sintaxe da estrutura try-catch-finally dentro do código Java:

<div align="center"><img src="https://i.imgur.com/hORZemU.png" title="source: imgur.com" /></div>

<h2>2. Implementando a captura de exceções na Classe Divisao</h2>

Veja a implementação abaixo:

```java
package com.generation.exc_divisao;

import java.util.InputMismatchException;
import java.util.Scanner;

public class Divisao {

	static Scanner ler = new Scanner(System.in);
	
	public static void main(String[] args) {
		
		int dividendo = 0;
		int divisor = 0;
		boolean loop = true;
		
		do {
			
			try {
				System.out.println("Digite o Dividendo: ");
				dividendo = ler.nextInt();
						
				System.out.println("Digite o Divisor: ");
				divisor = ler.nextInt();
						
				divide(dividendo, divisor);
				
				loop = false;
				
			}catch(InputMismatchException e){
				System.err.println("\nExceção: " + e);
				ler.nextLine();
				System.out.println("\nDigite valores inteiros!");
			}catch(ArithmeticException e){
				System.err.println("\nExceção: " + e);
				ler.nextLine();
				System.out.println("\nDigite Numeros inteiros positivos!");
			}
		
		}while (loop);
	}

	public static void divide(int dividendo, int divisor) {
		System.out.println("Divisão = " + (dividendo / divisor));
	}

}
```

A variável e recebe o tipo de exceção que aconteceu. A sua exibição na tela é opcional. Na sequência é exibida uma mensagem de alerta e o programa é reiniciado, como podemos ver na imagem abaixo, indicado pelas setas coloridas:

<div align="center"><img src="https://i.imgur.com/l0YECYu.png" title="source: imgur.com" /></div>



<h2>3. Throws e Throw</h2>

A **cláusula throws** especifica as **exceções que um método pode lançar**. Ele é inserida na assinatura do Método, depois da lista de parâmetros do método e antes do corpo do método. A cláusula throws contém uma lista separada por vírgulas das exceções. As exceções podem ser lançadas pelas instruções no corpo do método ou pelos métodos chamados. Veja o exemplo abaixo:

```java
	public static void divide(int dividendo, int divisor) throws ArithmeticException {
		System.out.println("Divisão = " + (dividendo / divisor));
	}
```

A **cláusula throw lança uma exceção em qualquer ponto do código**, mas não exige que ela seja tratada por seus chamadores. Ela transfere o  controle do fluxo para os métodos chamadores. Ela usa o que se chama  **unckecked exception**, ou seja, uma exceção é lançada mas nada obriga ela  ser tratada. Veja o exemplo abaixo:

1. Vamos criar um novo projeto. Dentro do Projeto, vamos criar uma Classe chamada **ExcecaoSimples**, contendo uma Exception personalizada:

```java
package array_exception.exception;

public class ExcecaoSimples extends Exception {

	private static final long serialVersionUID = 1L;
	
	public ExcecaoSimples () {}
    
	public ExcecaoSimples (String mensagem) {
		super(mensagem);
	}
}
```

2. Insira a **Classe Array**, como mostra o código abaixo:

```java
package array_exception;

import array_exception.exception.ExcecaoSimples;

public class Array {

	public static void main(String[] args) throws ExcecaoSimples{
		
		String nomes [] = {"João", "Maria", "Pedro", "Manuela"};
		
		try {
			for (int i=0;i<nomes.length;i++) {
				System.out.println(nomes[i]);
			}
		}catch (ArrayIndexOutOfBoundsException e) {
			System.err.println("\nExceção: " + e);
			System.out.println("\nPosição Inválida");
		}
		
		throw new ExcecaoSimples("Exceção Simples!");
	
	}
	
}
```

Observe que o final do código, na linha **throw new ExcecaoSimples("Exceção Simples!")**, estamos lançando a exceção criada a na **Classe ExcecaoSimples**. Veja o resultado no console abaixo:

<div align="center"><img src="https://i.imgur.com/dZ2rsnQ.png" title="source: imgur.com" /></div>

<h2>4. Hierarquia das Exceptions</h2>

<div align="center"><img src="https://www.oracle.com/technetwork/es/images/img1-5928057.png" title="source: imgur.com" /></div>

- **Throwable:** É a mãe de todas as exceções.
- **Error:** Não são exceções, e sim erros que jamais poderiam ter acontecido, como estouro da memória, por exemplo.
- **Exception:** São as classes que deveriam aqui, lançar exceções e não erros de programação. Exemplo: tentar abrir um arquivo que não existe. Então, é lançada uma exceção verificada, porque a classe de leitura de arquivos deriva de Exception.
- **RuntimeException**: São exceções que indicam erros de programas (não de lógica, pois senão não passaria pelo compilador). Esse tipo de exceção é conhecida como não verificada. 

<br /><br />

<div align="left"><a href="README.md"><img src="https://i.imgur.com/XMgF3gl.png" title="source: imgur.com" width="3%"/>Voltar</a></div>
